## **Predicting purchase probabilities**

### **Loading the data**

In [1]:
import numpy as np
import pandas as pd

from classes import Helper, Purchase_Probabilities

In [2]:
DATA_PATH = '/Users/leonhagel/Documents/coding/github/mlim-g2/data/'
EXPORT_PATH = '/Users/leonhagel/Documents/coding/github/mlim-g2/export/'

### **Preparing the full data set**

In [3]:
files = {
    'data': [
        #DATA_PATH + 'baskets.parquet',
        #DATA_PATH + 'coupon_index.parquet', 
        #DATA_PATH + 'coupons.parquet', 
        DATA_PATH + 'merged.parquet',
        #DATA_PATH + 'clean.parquet', 
        #DATA_PATH + 'purchase.parquet'
    ], 
    'mappings': [
        EXPORT_PATH + 'product_histories.parquet',
        EXPORT_PATH + 'prices.parquet',
    ]
}

In [4]:
## preparing the full data sets (elapsed time 313:27)
purchase = Purchase_Probabilities()
purchase.load(files)

# reduce file sizes
for name, df in purchase.data.items():
    purchase.data[name] = purchase.reduce_data_size(purchase.data[name])
    
# clean the data
purchase.data['clean'] = purchase.clean()

# preparing the data
df = 'clean' #None
shopper = (0, 1999)
week = (1, 89)
product = (0, 249)
price_aggregation_fn = 'mode'

purchase.data['purchase'] = purchase.prepare(df, shopper, week, product, price_aggregation_fn)
purchase.dump(DATA_PATH, which='data')
purchase.data['purchase']

[prepare] itertools... (elapsed time: 00:00)
[prepare] merge... (elapsed time: 01:13)
[prepare] cleaning... (elapsed time: 01:36)

100%|██████████| 43136548/43136548 [56:19<00:00, 12764.78it/s]
  0%|          | 0/44500000 [00:00<?, ?it/s]

[prepare] feature creation... (elapsed time: 58:13)

100%|██████████| 44500000/44500000 [38:51<00:00, 19090.33it/s]
100%|██████████| 44500000/44500000 [1:00:56<00:00, 12171.23it/s]
100%|██████████| 44500000/44500000 [52:33<00:00, 14110.39it/s]
100%|██████████| 44500000/44500000 [50:11<00:00, 14775.92it/s]
100%|██████████| 44500000/44500000 [52:36<00:00, 14099.56it/s]

[prepare] done (elapsed time: 313:27)

,shopper,week,product,price,discount,purchased,weeks_since_last_purchase,trend_1,trend_3,trend_5,product_freq
0,0,1,0,688.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
1,0,1,1,560.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
2,0,1,2,773.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
3,0,1,3,722.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
4,0,1,4,620.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
44499995,1999,89,245,549.0,0.0,1.0,19.0,0.0,0.0,0.0,0.123596
44499996,1999,89,246,702.0,0.3,0.0,103.0,0.0,0.0,0.0,0.000000
44499997,1999,89,247,670.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
44499998,1999,89,248,490.0,0.0,0.0,103.0,0.0,0.0,0.0,0.000000
44499999,1999,89,249,499.0,0.0,0.0,34.0,0.0,0.0,0.0,0.089888